spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    output:
      ansi:
        enabled: always

  datasource:
     driver-class-name: org.h2.Driver
     url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
     username: ""
     password: ""


server:
  port: 7777

