spring:
  jpa:
    output:
      ansi:
        enabled: always
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui






